repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: '.*\.vhd$'
      - id: end-of-file-fixer
        files: '.*\.vhd$'

# Disable automatic pre-commit hook installation
default_install_hook_types: []
